# Generated by Django 4.0.3 on 2022-05-24 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')])),
                ('month', models.CharField(choices=[('Ocak', 'Ocak'), ('Şubat', 'Şubat'), ('Mart', 'Mart'), ('Nisan', 'Nisan'), ('Mayıs', 'Mayıs'), ('Haziran', 'Haziran'), ('Temmuz', 'Temmuz'), ('Ağustos', 'Ağustos'), ('Eylül', 'Eylül'), ('Ekim', 'Ekim'), ('Kasım', 'Kasım'), ('Aralık', 'Aralık')], max_length=10)),
                ('type', models.CharField(choices=[('EFT', 'EFT'), ('HAVALE', 'HAVALE'), ('KREDİ', 'KREDİ')], max_length=10)),
                ('adminnote', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Eksik', 'Eksik'), ('Fazla', 'Fazla'), ('Tamam', 'Tamam'), ('İptal', 'İptal'), ('Red', 'Red')], default='Yeni', max_length=10)),
                ('payment', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
