# Generated by Django 4.0.3 on 2022-05-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_content_slug_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Haber', 'Haber'), ('Duyuru', 'Duyuru'), ('Etkinlik', 'Etkinlik'), ('Kararlar', 'Kararlar'), ('Anket', 'Anket'), ('Yönetim', 'Yönetim')], max_length=10),
        ),
    ]
