# Generated by Django 4.0.3 on 2022-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_content_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Haber', 'Haber'), ('Duyuru', 'Duyuru'), ('Etkinlik', 'Etkinlik'), ('Kararlar', 'Kararlar'), ('Anket', 'Anket'), ('Yonetim', 'Yonetim'), ('Sakin', 'Sakin')], max_length=10),
        ),
    ]
